name: Live Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Deploy
      run: |
        sshpass -p "${{ secrets.PWD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USR }}@${{ secrets.HOST }} << 'EOF'
          cd PapStore
          git fetch
          git pull
          npm install
          npm run build
          npx pm2 restart 2
        EOF
